title = "倾旋的博客"
baseURL = "https://payloads.online"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
googleAnalytics = ""
rssLimit = 20

[params]
  author = "倾旋"
  description = "倾旋的博客"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  plantuml = true
  [params.footer]
    text = "- PAYLOADS.ONLINE -"
    url = "https://payloads.online"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/Rvn0xsy"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:rvn0xsy@gmail.com"



[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/post/"
  [[menu.main]]
    name = "Rss"
    url = "/index.xml"
  [[menu.main]]
    name = "Links"
    url = "/links/"
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
  [[menu.main]]
    pre = "<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-terminal-fill" viewBox="0 0 16 16"><path d="M0 3a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3zm9.5 5.5h-3a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1zm-6.354-.354a.5.5 0 1 0 .708.708l2-2a.5.5 0 0 0 0-.708l-2-2a.5.5 0 1 0-.708.708L4.793 6.5 3.146 8.146z"/></svg>"
    name = "Projects"
    url = "/projects/"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5

