title = "倾旋的博客"
baseURL = "https://payloads.online"
theme = "researcher"
enableEmoji = true
googleAnalytics = ""
rssLimit = 20

[params]
  author = "倾旋"
  description = "倾旋的博客"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  plantuml = true
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/Rvn0xsy"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:rvn0xsy@gmail.com"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/Rvn0xsy"


[menu]
  [[menu.main]]
    pre = "fa fa-file-alt"
    name = "Posts"
    url = "/post/"
  [[menu.main]]
    pre = "fa fa-rss-square"
    name = "Rss"
    url = "/index.xml"
  [[menu.main]]
    pre = "fas fa-link"
    name = "Links"
    url = "/links/"
  [[menu.main]]
    pre = "fas fa-tools"
    name = "Tools"
    url = "/tools/"
  [[menu.main]]
    pre = "fas fa-code"
    name = "Projects"
    url = "/projects/"
    weight = 2

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files